const EPS=1e-10,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const C=(re=0,im=0)=>({re,im}),add=(a,b)=>C(a.re+b.re,a.im+b.im),sub=(a,b)=>C(a.re-b.re,a.im-b.im),mul=(a,b)=>C(a.re*b.re-a.im*b.im,a.re*b.im+a.im*b.re),conj=a=>C(a.re,-a.im),div=(a,b)=>{const d=b.re*b.re+b.im*b.im||EPS;return C((a.re*b.re+a.im*b.im)/d,(a.im*b.re-a.re*b.im)/d)},abs=a=>Math.hypot(a.re,a.im),polar=(r,a)=>C(r*Math.cos(a),r*Math.sin(a));
const solveLinear=(A,b)=>{const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[p][k]))p=i;[M[k],M[p]]=[M[p],M[k]];if(Math.abs(M[k][k])<1e-12)throw Error("Matriz singular");for(let i=k+1;i<n;i++){const f=M[i][k]/M[k][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j]}}const x=Array(n);for(let i=n-1;i>=0;i--){let v=M[i][n];for(let j=i+1;j<n;j++)v-=M[i][j]*x[j];x[i]=v/M[i][i]}return x};
const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),project=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy||1,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1);return{x:a.x+t*dx,y:a.y+t*dy,t,dist:Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)}};
function terminals(o){const z=o.scale||1,r=(o.rotation||0)*Math.PI/180,rot=(x,y)=>({x:o.x+x*Math.cos(r)-y*Math.sin(r),y:o.y+x*Math.sin(r)+y*Math.cos(r)});if(o.type==="breaker"||o.type==="disconnector")return[rot(0,-22*z),rot(0,22*z)];if(o.type==="transformer")return[rot(0,-44*z),rot(0,44*z)];if(o.type==="turbogenerator")return[rot(18*z,-40*z)];if(o.type==="utility"||o.type==="load"||o.type==="capacitor")return[rot(0,o.type==="utility"?-40*z:-34*z)];return[{x:o.x1,y:o.y1},{x:o.x2,y:o.y2}]}
const defaults=o=>{const e=o.electrical||{};return{nominalKV:13.8,frequencyHz:60,resistanceOhm:.02,reactanceOhm:.04,ampacityA:1000,ratedMVA:25,impedancePercent:10,tapPercent:0,activePowerMW:1,powerFactor:.9,loadNature:"inductive",capacitorMvar:5,capacitorStages:1,generatorRatedMVA:35,generationMW:20,generationMvar:0,gridRatedMVA:500,voltageSetpointPU:1,...e}};
function buildCase(diagram,baseMVA=100){const entries=Object.entries(diagram.items||{}),conductors=entries.filter(([,o])=>o.type==="line"||o.type==="bus"),electrical=entries.filter(([,o])=>!["annotationLine","area","text"].includes(o.type)),nodes=[];const node=p=>{let i=nodes.findIndex(n=>d(n,p)<=10);if(i<0){i=nodes.length;nodes.push({x:p.x,y:p.y})}return i},parent=[];const root=x=>{parent[x]??=x;return parent[x]===x?x:parent[x]=root(parent[x])},union=(a,b)=>{a=root(a);b=root(b);if(a!==b)parent[b]=a};const cuts=new Map;
for(const[k,o]of conductors){const [a,b]=terminals(o),pts=[{...a,t:0},{...b,t:1}];for(const[j,x]of electrical){if(j===k)continue;for(const p of terminals(x)){const q=project(p,a,b);if(q.dist<=20)pts.push(q)}}pts.sort((a,b)=>a.t-b.t);cuts.set(k,pts.filter((p,i)=>!i||Math.abs(p.t-pts[i-1].t)>.001))}
for(const pts of cuts.values())for(const p of pts)node(p);for(const[,o]of electrical)for(const p of terminals(o))node(p);nodes.forEach((_,i)=>parent[i]=i);
for(const[k,o]of conductors)if(o.type==="bus"){const ns=cuts.get(k).map(node);for(let i=1;i<ns.length;i++)union(ns[i-1],ns[i])}
for(const[,o]of electrical)if((o.type==="breaker"||o.type==="disconnector")&&o.state==="closed"){const t=terminals(o);union(node(t[0]),node(t[1]))}
const roots=[...new Set(nodes.map((_,i)=>root(i)))],index=new Map(roots.map((r,i)=>[r,i])),busOfPoint=p=>{let best=0,bd=Infinity;nodes.forEach((n,i)=>{const x=d(n,p);if(x<bd){bd=x;best=i}});return index.get(root(best))},nBus=roots.length,buses=Array.from({length:nBus},(_,i)=>({id:i,type:"PQ",name:"B"+(i+1),kv:13.8,p:0,q:0,v:1,angle:0,qMin:-Infinity,qMax:Infinity})),branches=[],busOfItem=new Map();
for(const[k,o]of conductors){const pts=cuts.get(k),ns=pts.map(busOfPoint),e=defaults(o),total=Math.max(EPS,d(pts[0],pts[pts.length-1]));if(o.type==="line")for(let i=0;i<ns.length-1;i++)if(ns[i]!==ns[i+1]){const ratio=d(pts[i],pts[i+1])/total;branches.push({from:ns[i],to:ns[i+1],r:Math.max(1e-7,e.resistanceOhm*ratio)*baseMVA/(e.nominalKV*e.nominalKV),x:Math.max(1e-7,e.reactanceOhm*ratio)*baseMVA/(e.nominalKV*e.nominalKV),b:0,tap:1,itemId:k,type:"line",ampacityA:e.ampacityA,kv:e.nominalKV})}busOfItem.set(k,ns[0]);for(const b of new Set(ns))buses[b].kv=e.nominalKV}
for(const[k,o]of electrical){if(o.type==="line"||o.type==="bus"||o.type==="breaker"||o.type==="disconnector")continue;const t=terminals(o),bi=busOfPoint(t[0]),e=defaults(o);busOfItem.set(k,bi);buses[bi].kv=o.type==="transformer"?e.primaryKV:e.nominalKV||buses[bi].kv;if(o.name)buses[bi].name=o.name;if(o.type==="load"&&o.state==="active"){const p=(+e.activePowerMW||0)*(o.runtimeScale??1),pf=clamp(+e.powerFactor||1,.1,1),q=p*Math.tan(Math.acos(pf))*(e.loadNature==="capacitive"?-1:e.loadNature==="resistive"?0:1);buses[bi].p-=p/baseMVA;buses[bi].q-=q/baseMVA}else if(o.type==="capacitor"){const stages=Math.max(0,Math.min(+e.capacitorStages||1,o.activeStages??(+e.capacitorStages||1)));buses[bi].q+=(+e.capacitorMvar||0)*stages/Math.max(1,+e.capacitorStages||1)/baseMVA}else if(o.type==="turbogenerator"&&o.state!=="stopped"&&o.isSource!==false){buses[bi].p+=(o.controlMode==="manual"?+o.manualGenerationMW||0:(+e.generationMW||0)*(o.runtimeScale??1))/baseMVA;buses[bi].v=1;if(buses[bi].type!=="Slack")buses[bi].type="PV";buses[bi].qMin=-(+e.generatorRatedMVA||35)/baseMVA;buses[bi].qMax=(+e.generatorRatedMVA||35)/baseMVA}else if(o.type==="utility"&&o.state!=="stopped"&&o.isSource!==false){buses[bi].type="Slack";buses[bi].v=+e.voltageSetpointPU||1;buses[bi].angle=0}else if(o.type==="transformer"){const bj=busOfPoint(t[1]);busOfItem.set(k,bi);const z=Math.max(.001,+e.impedancePercent||10)/100,r=z*.1,x=Math.sqrt(Math.max(EPS,z*z-r*r)),tap=1+(+e.tapPercent||0)/100;branches.push({from:bi,to:bj,r,x,b:0,tap,itemId:k,type:"transformer",ratedMVA:e.ratedMVA,kv:e.secondaryKV});buses[bi].kv=e.primaryKV;buses[bj].kv=e.secondaryKV}}
if(!buses.some(b=>b.type==="Slack")){const pv=buses.find(b=>b.type==="PV");if(pv)pv.type="Slack";else if(buses[0])buses[0].type="Slack"}return{baseMVA,buses,branches,busOfItem}}
function yBus(c){const n=c.buses.length,Y=Array.from({length:n},()=>Array.from({length:n},()=>C()));for(const br of c.branches){const y=div(C(1),C(br.r,br.x)),tap=br.tap||1,bsh=C(0,br.b/2);Y[br.from][br.from]=add(Y[br.from][br.from],div(add(y,bsh),C(tap*tap)));Y[br.to][br.to]=add(Y[br.to][br.to],add(y,bsh));const off=div(y,C(tap));Y[br.from][br.to]=sub(Y[br.from][br.to],off);Y[br.to][br.from]=sub(Y[br.to][br.from],off)}return Y}
const injections=(V,Y)=>V.map((v,i)=>{let I=C();for(let j=0;j<V.length;j++)I=add(I,mul(Y[i][j],V[j]));const S=mul(v,conj(I));return{p:S.re,q:S.im}});
function mismatch(c,V,Y){const calc=injections(V,Y),nonSlack=[],pq=[];c.buses.forEach((b,i)=>{if(b.type!=="Slack")nonSlack.push(i);if(b.type==="PQ")pq.push(i)});return{vec:[...nonSlack.map(i=>c.buses[i].p-calc[i].p),...pq.map(i=>c.buses[i].q-calc[i].q)],nonSlack,pq,calc}}
function newton(c,opt={}){const Y=yBus(c),n=c.buses.length,V=c.buses.map(b=>polar(b.v||1,b.angle||0)),tol=opt.tolerance||1e-7,max=opt.maxIterations||30;let converged=false,iteration=0;for(;iteration<max;iteration++){const m=mismatch(c,V,Y),err=Math.max(0,...m.vec.map(Math.abs));if(err<tol){converged=true;break}const vars=[...m.nonSlack.map(i=>({i,k:"a"})),...m.pq.map(i=>({i,k:"v"}))],h=1e-5,J=Array.from({length:m.vec.length},()=>Array(vars.length));for(let j=0;j<vars.length;j++){const x=vars[j],Vp=V.map(z=>C(z.re,z.im)),mag=abs(Vp[x.i]),ang=Math.atan2(Vp[x.i].im,Vp[x.i].re);Vp[x.i]=x.k==="a"?polar(mag,ang+h):polar(mag+h,ang);const mp=mismatch(c,Vp,Y).vec;for(let i=0;i<m.vec.length;i++)J[i][j]=(mp[i]-m.vec[i])/h}const dx=solveLinear(J,m.vec.map(v=>-v));vars.forEach((x,j)=>{const mag=abs(V[x.i]),ang=Math.atan2(V[x.i].im,V[x.i].re);V[x.i]=x.k==="a"?polar(mag,ang+dx[j]):polar(Math.max(.5,mag+dx[j]),ang)})}return finish(c,V,Y,converged,iteration,"Newton-Raphson")}
function gaussSeidel(c,opt={}){const Y=yBus(c),V=c.buses.map(b=>polar(b.v||1,b.angle||0)),tol=opt.tolerance||1e-7,max=opt.maxIterations||200;let converged=false,iteration=0;for(;iteration<max;iteration++){let err=0;for(let i=0;i<V.length;i++){const b=c.buses[i];if(b.type==="Slack")continue;let sum=C();for(let j=0;j<V.length;j++)if(j!==i)sum=add(sum,mul(Y[i][j],V[j]));let q=b.q;if(b.type==="PV")q=injections(V,Y)[i].q;const next=div(sub(div(C(b.p,-q),conj(V[i])),sum),Y[i][i]);const nv=b.type==="PV"?polar(b.v,Math.atan2(next.im,next.re)):next;err=Math.max(err,abs(sub(nv,V[i])));V[i]=nv}if(err<tol){converged=true;break}}return finish(c,V,Y,converged,iteration,"Gauss-Seidel")}
function decoupled(c,opt={}){const Y=yBus(c),V=c.buses.map(b=>polar(b.v||1,b.angle||0)),tol=opt.tolerance||1e-7,max=opt.maxIterations||80,ns=c.buses.map((b,i)=>b.type!=="Slack"?i:null).filter(i=>i!==null),pq=c.buses.map((b,i)=>b.type==="PQ"?i:null).filter(i=>i!==null),Bp=ns.map(i=>ns.map(j=>-Y[i][j].im)),Bq=pq.map(i=>pq.map(j=>-Y[i][j].im));let converged=false,iteration=0;for(;iteration<max;iteration++){let m=mismatch(c,V,Y),err=Math.max(0,...m.vec.map(Math.abs));if(err<tol){converged=true;break}if(ns.length){const dp=ns.map((i,k)=>m.vec[k]/Math.max(.2,abs(V[i]))),da=solveLinear(Bp,dp);ns.forEach((i,k)=>V[i]=polar(abs(V[i]),Math.atan2(V[i].im,V[i].re)+da[k]))}m=mismatch(c,V,Y);if(pq.length){const dq=pq.map((i,k)=>m.vec[ns.length+k]/Math.max(.2,abs(V[i]))),dv=solveLinear(Bq,dq);pq.forEach((i,k)=>V[i]=polar(Math.max(.5,abs(V[i])+dv[k]),Math.atan2(V[i].im,V[i].re)))}}return finish(c,V,Y,converged,iteration,"Desacoplado rápido")}
function finish(c,V,Y,converged,iterations,method){const inj=injections(V,Y),branches=c.branches.map(br=>{const y=div(C(1),C(br.r,br.x)),Vi=V[br.from],Vj=V[br.to],tap=br.tap||1,Iij=mul(sub(div(Vi,C(tap)),Vj),y),Iji=mul(sub(Vj,div(Vi,C(tap))),y),Sij=mul(Vi,conj(Iij)),Sji=mul(Vj,conj(Iji));return{...br,pFromMW:Sij.re*c.baseMVA,qFromMvar:Sij.im*c.baseMVA,pToMW:Sji.re*c.baseMVA,qToMvar:Sji.im*c.baseMVA,lossMW:(Sij.re+Sji.re)*c.baseMVA,lossMvar:(Sij.im+Sji.im)*c.baseMVA,currentA:abs(Iij)*c.baseMVA*1e6/(Math.sqrt(3)*Math.max(.1,br.kv||c.buses[br.from].kv)*1000)}});return{method,converged,iterations,ybus:Y,buses:c.buses.map((b,i)=>({...b,voltagePU:abs(V[i]),angleDeg:Math.atan2(V[i].im,V[i].re)*180/Math.PI,pCalculatedMW:inj[i].p*c.baseMVA,qCalculatedMvar:inj[i].q*c.baseMVA})),branches,totalLossMW:branches.reduce((a,b)=>a+b.lossMW,0),totalLossMvar:branches.reduce((a,b)=>a+b.lossMvar,0),caseData:c}}
export function solveDiagramPowerFlow(diagram,{method="newton",baseMVA=100,tolerance=1e-7,maxIterations}={}){const c=buildCase(diagram,baseMVA);if(c.buses.length<2||!c.branches.length)throw Error("Rede insuficiente: conecte pelo menos duas barras por uma linha ou transformador.");if(method==="gauss")return gaussSeidel(c,{tolerance,maxIterations});if(method==="decoupled")return decoupled(c,{tolerance,maxIterations});return newton(c,{tolerance,maxIterations})}
export{buildCase,yBus};